[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"
  environment = { NODE_ENV = "production" }


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
